apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-range
  namespace: se-dalab
spec:
  limits:
  - default:
      cpu: 1
    defaultRequest:
      cpu: 0.5
    type: Container
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: se-dalab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: front-end
    spec:
      # Make the service externally visible via the node
      containers:
      - name: front-end
        image: front-end
        imagePullPolicy: Never
        ports:
        - name: front-end
          containerPort: 8081
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
     # nodeSelector:
      #  beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: se-dalab
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 30002
  selector:
    name: front-end
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: people
  labels:
    name: people
  namespace: se-dalab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: people
    spec:
      # Make the service externally visible via the node
      containers:
      - name: people
        image: se-course-people
        imagePullPolicy: Never
        ports:
        - name: people
          containerPort: 8082
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
     # nodeSelector:
      #  beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: people
  labels:
    name: people
  namespace: se-dalab
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8082
    nodePort: 30003
  selector:
    name: people
---